CREATE DATABASE IF NOT EXISTS `spider`
DEFAULT CHARACTER SET utf8mb4;

USE `spider`;
CREATE TABLE IF NOT EXISTS `queue`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `path` VARCHAR (255) NOT NULL,
    `mask` VARCHAR (255) NOT NULL,
    PRIMARY KEY(`id`))
;
CREATE TABLE IF NOT EXISTS `pid_table` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `pid` INT NOT NULL,
    PRIMARY KEY(`id`))
;